plugins {
    id 'com.android.application'
}

android {
    namespace 'com.huhx0015.hxaudiodemo'
    compileSdk 37

    defaultConfig {
        applicationId "com.huhx0015.huhxagse"
        minSdk 14
        targetSdk 25
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {

    // INTEGRATED LIBRARIES:
    implementation project(':hxaudio')

    // ANDROID SUPPORT LIBRARIES:
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.cardview:cardview:1.0.0'
}
