plugins {
    id 'com.android.library'
}

android {
    namespace 'com.huhx0015.hxaudio'
    compileSdk 37

    defaultConfig {
        minSdk 21
        targetSdk 37
        versionCode 24
        versionName "4.0.1"
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}